steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  - name: gcr.io/cloud-builders/gcloud-slim
    args:
      - run
      - services
      - update
      - art-bot
      - '--platform=managed'
      - '--image=us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=us-east4'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - 'us.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - art-bot
